import type { ThemeDefinition } from './types'

export const budgetDefaultTheme: ThemeDefinition = {
  id: 'default',
  name: 'Default',
  palettes: {
    light: {
      canvas:       '#f8fafc',
      surface:      '#ffffff',
      surfaceAlt:   '#f1f5f9',
      hover:        '#e2e8f0',
      text:         '#1e293b',
      textMuted:    '#475569',
      textInverse:  '#ffffff',
      border:       '#e2e8f0',
      borderStrong: '#cbd5e1',
      accent:       '#1d4ed8',
      accentHover:  '#1e40af',
      accentSubtle: '#eff6ff',
      focus:        '#3b82f6',
      positive:     '#15803d',
      negative:     '#b91c1c',
      energyLowBg:       '#e8f0e5',
      energyLowAccent:   '#4a7a40',
      energyLowText:     '#1e3a18',
      energyMediumBg:    '#ddeaf8',
      energyMediumAccent:'#1d4ed8',
      energyMediumText:  '#1e3a6e',
      energyHighBg:      '#f0e8f8',
      energyHighAccent:  '#7c3aed',
      energyHighText:    '#3b1a6e',
    },
    dark: {
      canvas:       '#0f172a',
      surface:      '#1e293b',
      surfaceAlt:   '#334155',
      hover:        '#334155',
      text:         '#f1f5f9',
      textMuted:    '#94a3b8',
      textInverse:  '#ffffff',
      border:       '#334155',
      borderStrong: '#475569',
      accent:       '#60a5fa',
      accentHover:  '#3b82f6',
      accentSubtle: '#1e3a5f',
      focus:        '#60a5fa',
      positive:     '#4ade80',
      negative:     '#f87171',
      energyLowBg:       '#1a2e1a',
      energyLowAccent:   '#4ade80',
      energyLowText:     '#bbf7d0',
      energyMediumBg:    '#1e2e4a',
      energyMediumAccent:'#60a5fa',
      energyMediumText:  '#bfdbfe',
      energyHighBg:      '#2e1e4a',
      energyHighAccent:  '#a78bfa',
      energyHighText:    '#ddd6fe',
    },
  },
}
